export const listings = [
  {
    id: 1,
    image: "/nft/orange-ranger.png",
    background: "/nft/nft-background-orange.png",
    title: "Orange Ranger",
    date: "12 Feb 2024, 13:32",
    qty: 241,
    btcPrice: 0.0018,
    usdPrice: 120.0,
  },
  {
    id: 2,
    image: "/nft/founders-drop-vault.png",
    background: "/nft/nft-background-gold.png",
    title: "Founders Drop Vault",
    date: "10 Feb 2024, 13:32",
    qty: 153,
    btcPrice: 0.0003,
    usdPrice: 20.0,
  },
  {
    id: 3,
    image: "/nft/halloween-drop-vault.png",
    background: "/nft/nft-background-purple.png",
    title: "Halloween Drop Vault",
    date: "9 Feb 2024, 13:32",
    qty: 2,
    btcPrice: 0.03,
    usdPrice: 2000.0,
  },
  {
    id: 4,
    image: "/nft/alien-drop-vault.png",
    background: "/nft/nft-background-orange.png",
    title: "Alien Drop Vault",
    date: "16 Feb 2024, 13:32",
    qty: 52,
    btcPrice: 0.0032,
    usdPrice: 214.0,
  },
  {
    id: 5,
    image: "/nft/digitek-drop-vault.png",
    background: "/nft/nft-background-orange.png",
    title: "Digitek Drop Vault",
    date: "12 Feb 2024, 13:32",
    qty: 241,
    btcPrice: 0.0032,
    usdPrice: 211.02,
  },
];
